POST http://localhost:5000/user/register
Content-Type: application/json

{
  "name": "Nirmal",
  "email": "nirmal@gmail.com",
  "password": "Nirmal@123",
  "role": "user",
  "isVerified": false
}

###
POST http://localhost:5000/user/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY3NjEyNjU1LCJleHAiOjE3Njc2OTkwNTV9.7TvgPSbcE8q7xa5wAOXAQf5YBuSM4VsztbpatOH5ggM

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
   "email": "nirmal@gmail.com",
   "password": "Nirmal@123"
}
// token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksImlhdCI6MTc2NzUxMzQ1NSwiZXhwIjoxNzY3NTk5ODU1fQ.ps4KU6A8fTVaCrYJ05nM-GTVNtDgBY9KrSDS3ByACMA

###
POST http://localhost:5000/user/verify-otp
Content-Type: application/json

{
  "email" : "nirmal@gmail.com",
  "otp" : "418342"
}